_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 5
                - 53
                - 55
                - 105
            "2":
                - 5
                - 53
                - 55
                - 105
            "3":
                - 13
                - 23
                - 24
                - 55
            "4": 3.10.15
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
model:
    value: DecisionTree
random_state:
    value: 42
